services:
  # Database Service
  postgres:
    image: postgres:15-alpine
    container_name: sharednotes-postgres
    environment:
      POSTGRES_DB: sharednotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - sharednotes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Authentication Service (Keycloak)
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: sharednotes-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres123
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - postgres
    networks:
      - sharednotes-network

  # Backend Services
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: sharednotes-gateway
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=sharednotes
      - KEYCLOAK_CLIENT_ID=sharednotes-api
      - NOTES_SERVICE_URL=http://notes-service:8002
    depends_on:
      - keycloak
      - notes-service
    networks:
      - sharednotes-network

  notes-service:
    build:
      context: ./backend/notes-service
      dockerfile: Dockerfile
    container_name: sharednotes-notes
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/sharednotes
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=sharednotes
      - KEYCLOAK_ADMIN_CLIENT_ID=admin-cli
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    depends_on:
      - postgres
      - keycloak
    networks:
      - sharednotes-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sharednotes-frontend
    ports:
      - "3000:3000"  # HTTP redirect to HTTPS
      - "3443:3443"  # HTTPS frontend entry point
    volumes:
      - ./certs:/app/certs:ro  # Mount SSL certificates
    depends_on:
      - api-gateway
    networks:
      - sharednotes-network

volumes:
  postgres_data:

networks:
  sharednotes-network:
    driver: bridge
